version: "3.8"

x-db-vars: &db-vars
    POSTGRES_HOST: "db"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_DB: "postgres"
    PGDATA: "var/lib/postgresql/data"

services: 
    server: 
        build: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
        environment: 
            <<: *db-vars
            
volumes:
    db:
    