version: "3.8"

services: 
    server: 
        build: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres