# Generated by Django 4.2 on 2023-09-29 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("add_teammate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="joined_date",
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
